name: Lighthouse CI

on: deployment_status

jobs:
  lighthouse:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://mery182.github.io/animation_vue/
            https://mery182.github.io/animation_vue/js
            https://mery182.github.io/animation_vue/anime
            https://mery182.github.io/animation_vue/gsap
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
